import csv
import random

def f_584(file_path,
          num_rows,
          gender=['Male', 'Female', 'Non-Binary'],
          countries=['USA', 'UK', 'Canada', 'Australia', 'India'],
          seed=None):
    """
    Generates a CSV file with random data for the fields ['Name', 'Age', 'Gender', 'Country'].
    The number of rows in the CSV file is determined by the 'num_rows' parameter.

    The Ages are randomly sampled integers in the range [20, 60].
    The names are generated by randomly choosing 5 uppercase characters from the english alphabet.

    
    If num_rows <= 0 a csv containing only the headers is generated.

    Parameters:
    file_path (str): The file path where the CSV file should be created.
    num_rows (int): The number of rows of random data to generate.
    gender (list of str, optional): The list of genders to sample from.
        Defaults to ['Male', 'Female', 'Non-Binary'].
    countries (list of str, optional): The list of countries to sample from.
        Defaults to ['USA', 'UK', 'Canada', 'Australia', 'India'].
    seed (int, optional): The seed used for random sampling.
        Defaults to None.

    Returns:
    str: The file path of the generated CSV file.

    Requirements:
    - csv
    - random

    Example:
    >>> f_584('/tmp/data.csv', 100)
    '/tmp/data.csv'

    >>> f_584('/test.csv', 100, gender=['test'], countries['Albania', 'Germany', 'Austria'], seed=12)
    'test.csv'
    """
    FIELDS = ['Name', 'Age', 'Gender', 'Country']
    random.seed(seed)
    with open(file_path, 'w', newline='') as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=FIELDS)
        writer.writeheader()
        for _ in range(num_rows):
            writer.writerow({
                'Name': ''.join(random.choices('ABCDEFGHIJKLMNOPQRSTUVWXYZ', k=5)),
                'Age': random.randint(20, 60),
                'Gender': random.choice(gender),
                'Country': random.choice(countries)
            })
    return file_path

import unittest
import os
import csv
from faker import Faker
class TestCases(unittest.TestCase):
    fake = Faker()
    def setUp(self):
        self.file_path = self.generate_random_file_path()
    def tearDown(self):
        if os.path.exists(self.file_path):
            os.remove(self.file_path)
    def generate_random_file_path(self):
        return f"{self.fake.file_name(extension='csv')}"
    def test_case_1(self):
        rows = 10
        returned_path = f_584(self.file_path, rows, seed=12)
        self.assertTrue(os.path.exists(returned_path))
        expected = [['Name', 'Age', 'Gender', 'Country'],
   ['MRRDA', '43', 'Female', 'Canada'],
   ['QLWFA', '59', 'Male', 'Australia'],
   ['JIFOF', '52', 'Non-Binary', 'Canada'],
   ['RUCXV', '52', 'Male', 'USA'],
   ['ZLLRZ', '54', 'Female', 'India'],
   ['OZXON', '25', 'Female', 'India'],
   ['KPMJA', '25', 'Male', 'Canada'],
   ['JJRRC', '35', 'Female', 'Canada'],
   ['JOTEJ', '47', 'Male', 'India'],
  ['ARBFP', '55', 'Male', 'UK']]
        with open(returned_path, 'r') as csv_file:
            reader = csv.reader(csv_file)
            self.assertEqual(list(reader), expected)
    def test_case_2(self):
        rows = 1000
        returned_path = f_584(self.file_path, rows, seed=13)
        self.assertTrue(os.path.exists(returned_path))
        with open(returned_path, 'r') as csv_file:
            reader = csv.reader(csv_file)
            self.assertEqual(len(list(reader)), rows + 1)
    def test_case_3(self):
        rows = 0
        returned_path = f_584(self.file_path, rows, seed=123)
        self.assertTrue(os.path.exists(returned_path))
        with open(returned_path, 'r') as csv_file:
            reader = csv.reader(csv_file)
            self.assertEqual(list(reader), [['Name', 'Age', 'Gender', 'Country']])
    def test_case_4(self):
        rows = -10
        returned_path = f_584(self.file_path, rows, seed=221)
        self.assertTrue(os.path.exists(returned_path))
        with open(returned_path, 'r') as csv_file:
            reader = csv.reader(csv_file)
            self.assertEqual(list(reader), [['Name', 'Age', 'Gender', 'Country']])
    def test_case_5(self):
        rows = 100
        returned_path = f_584(self.file_path, rows, seed=342)
        self.assertTrue(os.path.exists(returned_path))
        with open(returned_path, 'r') as csv_file:
            reader = csv.DictReader(csv_file)
            data = list(reader)
            self.assertEqual(len(data), rows)
            for row in data:
                self.assertIn(row['Gender'], ['Male', 'Female', 'Non-Binary'])
                self.assertIn(row['Country'], ['USA', 'UK', 'Canada', 'Australia', 'India'])
                self.assertTrue(20 <= int(row['Age']) <= 60)
                self.assertEqual(len(row['Name']), 5)
    def test_case_6(self):
        rows = 100
        returned_path = f_584(self.file_path, rows, seed=342, gender=['a', 'b'], countries=['Austria'])
        self.assertTrue(os.path.exists(returned_path))
        with open(returned_path, 'r') as csv_file:
            reader = csv.DictReader(csv_file)
            data = list(reader)
            self.assertEqual(len(data), rows)
            for row in data:
                self.assertIn(row['Gender'], ['a', 'b'])
                self.assertIn(row['Country'], ['Austria'])
                self.assertTrue(20 <= int(row['Age']) <= 60)
                self.assertEqual(len(row['Name']), 5)
